function [chassis,flwheel,frwheel,rlwheel,rrwheel,Laxis] = myCar(x,y,theta1,thetawheels1)
theta = twoRad(theta1);thetawheels = twoRad(thetawheels1);
% chassis plot
chassisx = [x-(0.5*cosd(180-theta)+0.7*cosd(theta-90)),...
    x-(0.5*cosd(180-theta)-0.7*cosd(theta-90)),...
    x+(0.5*cosd(180-theta)+0.7*cosd(theta-90))-2*cosd(-theta), ...
    x+(0.5*cosd(180-theta)-0.7*cosd(theta-90))-2*cosd(-theta)];
chassisy = [y+(0.7*cosd(theta)+0.5*sind(theta)),...
    y+(-0.7*cosd(theta)+0.5*sind(theta)),...
    y+(-0.7*cosd(theta)+0.5*sind(theta))-3*sind(theta),...
    y+(0.7*cosd(theta)+0.5*sind(theta))-3*sind(theta)];
chassis = [chassisx,chassisx(1);chassisy,chassisy(1)];
% front wheels plot
thetan = theta+thetawheels;
flwheelxc = x-0.5*cosd(theta-90);frwheelxc = x+0.5*cosd(theta-90);
flwheelyc = y+0.5*cosd(theta);frwheelyc = y-0.5*cosd(theta);
flwheelx = [flwheelxc+0.25*cosd(thetan)-0.1*sind(thetan),...
    flwheelxc+0.25*cosd(thetan)+0.1*sind(thetan),...
    flwheelxc-0.25*cosd(thetan)+0.1*sind(thetan),...
    flwheelxc-0.25*cosd(thetan)-0.1*sind(thetan)];
flwheely = [flwheelyc+0.1*cosd(thetan)+0.25*sind(thetan),...
    flwheelyc-0.1*cosd(thetan)+0.25*sind(thetan),...
    flwheelyc-0.1*cosd(thetan)-0.25*sind(thetan),...
    flwheelyc+0.1*cosd(thetan)-0.25*sind(thetan)];
flwheel = [flwheelx,flwheelx(1);flwheely,flwheely(1)];
frwheelx = [frwheelxc+0.25*cosd(thetan)-0.1*sind(thetan),...
    frwheelxc+0.25*cosd(thetan)+0.1*sind(thetan),...
    frwheelxc-0.25*cosd(thetan)+0.1*sind(thetan),...
    frwheelxc-0.25*cosd(thetan)-0.1*sind(thetan)];
frwheely = [frwheelyc+0.1*cosd(thetan)+0.25*sind(thetan),...
    frwheelyc-0.1*cosd(thetan)+0.25*sind(thetan),...
    frwheelyc-0.1*cosd(thetan)-0.25*sind(thetan),...
    frwheelyc+0.1*cosd(thetan)-0.25*sind(thetan)];
frwheel = [frwheelx,frwheelx(1);frwheely,frwheely(1)];
% rear wheels plot
rlwheelxc = x-0.5*cosd(theta-90)-2*cosd(theta);...
    rrwheelxc = x+0.5*cosd(theta-90)-2*cosd(theta);
rlwheelyc = y+0.5*cosd(theta)-2*sind(theta);...
    rrwheelyc = y-0.5*cosd(theta)-2*sind(theta);
rlwheelx = [rlwheelxc+0.25*cosd(theta)-0.13*sind(theta),...
    rlwheelxc+0.25*cosd(theta)+0.13*sind(theta),...
    rlwheelxc-0.25*cosd(theta)+0.13*sind(theta),...
    rlwheelxc-0.25*cosd(theta)-0.13*sind(theta)];
rlwheely = [rlwheelyc+0.13*cosd(theta)+0.25*sind(theta),...
    rlwheelyc-0.13*cosd(theta)+0.25*sind(theta),...
    rlwheelyc-0.13*cosd(theta)-0.25*sind(theta),...
    rlwheelyc+0.13*cosd(theta)-0.25*sind(theta)];
rlwheel = [rlwheelx,rlwheelx(1);rlwheely,rlwheely(1)];
rrwheelx = [rrwheelxc+0.25*cosd(theta)-0.13*sind(theta),...
    rrwheelxc+0.25*cosd(theta)+0.13*sind(theta),...
    rrwheelxc-0.25*cosd(theta)+0.13*sind(theta),...
    rrwheelxc-0.25*cosd(theta)-0.13*sind(theta)];
rrwheely = [rrwheelyc+0.13*cosd(theta)+0.25*sind(theta),...
    rrwheelyc-0.13*cosd(theta)+0.25*sind(theta),...
    rrwheelyc-0.13*cosd(theta)-0.25*sind(theta),...
    rrwheelyc+0.13*cosd(theta)-0.25*sind(theta)];
rrwheel = [rrwheelx,rrwheelx(1);rrwheely,rrwheely(1)];
% axis plot
axisx = [flwheelxc,frwheelxc,(flwheelxc+frwheelxc)/2,...
    (rlwheelxc+rrwheelxc)/2,rlwheelxc,rrwheelxc];
axisy = [flwheelyc,frwheelyc,(flwheelyc+frwheelyc)/2,...
    (rlwheelyc+rrwheelyc)/2,rlwheelyc,rrwheelyc];
Laxis = [axisx;axisy];
%% plots
hold on; grid on; grid minor;
plot(chassis(1,:),chassis(2,:),'b');
plot(flwheel(1,:),flwheel(2,:),'k');
plot(frwheel(1,:),frwheel(2,:),'k');
plot(rlwheel(1,:),rlwheel(2,:),'k');
plot(rrwheel(1,:),rrwheel(2,:),'k');
plot(Laxis(1,:),Laxis(2,:),'-.*');
p1 = [(rlwheelxc+rrwheelxc)/2+0.4*cosd(theta) ...
    (rlwheelyc+rrwheelyc)/2+0.4*sind(theta)];
p2 = [(flwheelxc+frwheelxc)/2-0.3*cosd(theta) ...
    (flwheelyc+frwheelyc)/2-0.3*sind(theta)];
dp = p2-p1;
quiver(p1(1),p1(2),dp(1),dp(2),'LineWidth',0.75,...
    'MaxHeadSize',0.5,'AutoScale','off','color','r');
end